# Avanza Stock Integration Services
# This file defines any custom services provided by the integration

# Currently no custom services are defined
# Services will be added here if needed in the future
