---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - id: changelog
        run: |
          curr_tag=$(git describe --tags --abbrev=0)
          prev_tag=$(git describe --tags --abbrev=0 $curr_tag^)
          echo "Previous tag: $prev_tag"
          echo "Current tag: $curr_tag"
          log="$(git log --format='- %h %s' $prev_tag..$curr_tag)"
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "::set-output name=body::$log"

      - uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes

            ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
